### ISSUE TITLE
log and ln are both calculated has ln

### ISSUE THREAD

**Issue by gagarine** [tranleduy2000/ncalc#1]
Their is a nasty bug: log and ln are both calculated has ln...

**Comment by EinBaum** [comment]
I think log should be base 10. That's what most users expect. Also it's pointless to have 2 functions ln and log if both do the same thing.

**Comment by tranleduy2000** [comment]
Thanks for report bug.

**Comment by axkr** [comment]
In computer algebra you have to use some kind of "normalization" to compare diferent objects for "equality".

For the `Ln, Log2` and `Log10` functions this could be achieved by a general `Log(z, base) `definition:

* https://github.com/axkr/symja_android_library/blob/master/symja_android_library/doc/functions/Log.md

**Comment by gagarine** [comment]
Some user may want log to be the natural log (mathematica take log as ln) see http://mathworld.wolfram.com/Ln.html

But I agree that most user except log to be base 10.

Perhaps, having a preference for that? And the first time the user use log or ln tell the user "we are taking log as log10, you can change that in the preferences".
