### ISSUE TITLE
Ncalc shows wrong result

### ISSUE THREAD

**Issue by poulpoulsen** [tranleduy2000/ncalc#10]
hello,
unfortunately sometimes ncalc shows a slightly wrong result.
E.G. subtract a value from another and the result should be a number with two digits right from decimalpoint. But ncalc shows a additional digit, though the result has more than two digits.
0,25 versus 0,25000000005.

Any clues?

Regards
Poul

**Comment by krzysdz** [comment]
@poulpoulsen Could you provide us with steps to reproduce the problem (like `type 0,35-0,1`), your app version and LaTeX engine used?

**Comment by jhotmann** [comment]
Seems to be a floating point rounding error.  It can be reproduced with something simple like:

```
1.3 - 1
> 0.30000000000000004
```

**Comment by poulpoulsen** [comment]
Hello there,

exactly here!
same wrong result.

Thanks
poul

**Comment by axkr** [comment]
The reason is the double floating point arithmetic.

If you run this snippet it will print 0.30000000000000004
```
		double a = 1.3;
		double b = 1.0;
		double result = a - b;
		// prints 0.30000000000000004
		System.out.println(result);
```
		
You can use DecimalFormat to print 0.3 
```
		DecimalFormatSymbols otherSymbols = new DecimalFormatSymbols(Locale.US);
		DecimalFormat decimalFormat = new DecimalFormat("0.0####", otherSymbols);
		// prints 0.3
		System.out.println(decimalFormat.format(result)); 
```

**Comment by visionok** [comment]
I was using NCalc+ to check my groceries bill when I came across this error. This is seriously broken for a calculator! The real solution is to use something like BCDs. Using something like DecimalFormat suggested above only hides the errors.
