### ISSUE TITLE
Feature Request: Simple Interest Calculator

### ISSUE THREAD

**Issue by geniusupgrader** [tranleduy2000/ncalc#18]

**Comment by axkr** [comment]
Can you please test this functions in Programming activity and comment:
- https://github.com/axkr/symja_android_library/blob/master/symja_android_library/doc/functions/Annuity.md
- https://github.com/axkr/symja_android_library/blob/master/symja_android_library/doc/functions/AnnuityDue.md
- https://github.com/axkr/symja_android_library/blob/master/symja_android_library/doc/functions/EffectiveInterest.md
- https://github.com/axkr/symja_android_library/blob/master/symja_android_library/doc/functions/TimeValue.md

**Comment by geniusupgrader** [comment]
Havn't seen this. Will close the issue, thanks
