### ISSUE TITLE
Themes are inconsistent

### ISSUE THREAD

**Issue by Madis0** [tranleduy2000/ncalc#21]
Hello, 
I think it is overall a pretty app, even somewhat better than the built-in one (proper FAB, haha), but I noticed the themes are quite inconsistent: 

- "Light" is exactly the same as "Cyan"
- Dark themes are mixed with light ones 
- No accent color setting, you never know what you get 
- "Gradient" only has one color 
- Some elements have persistent colors

And here's how I think it could be fixed:

- "Light", "Dark" and "Gradient" as base options 
- Separate color settings for primary and accent 
- FAB should use the primary color (because secondary is already used in a large area)
- Advanced doesn't need to be there (#22)

**Comment by axkr** [comment]
Fixed with 3.4.3-beta.

If necessary open a new issue with more details.
