### ISSUE TITLE
Please allow user keyboard input.

### ISSUE THREAD

**Issue by WulfricLee** [tranleduy2000/ncalc#26]
I saw there are a lot of functions in **All functions** inside of menu, but how can I use these functions? I can't input these functions with my own keyboard like using Python, I can only use the in-app keyboard, which only contains limited functions, so there is no way to input a function manually.

**Comment by lojzezust** [comment]
Bump. Manual (advanced) mode would be great. It's the only thing missing in my opinion. For example it is not clear how to use the Solve function in the Scientific Calculator mode. You can't use it the way it is described in the documentation, because you can't input the '=' character.

**Comment by ja72** [comment]
That was also my comment. How do I set a variable, like `a=10` to be used later in an equation?

**Comment by DeXtmL** [comment]
Since the author no longer work on this project, any solution so far?   This is the best calculator I found around, with only this core functionality missing from the UI

**Comment by axkr** [comment]
In version 3.4.1 there is now an IDE mode available.

**Comment by axkr** [comment]
In  IDE mode you can use a user keyboard.

For example if you have Hacker's Keyboard installed:
* https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard

it should work in IDE mode.
