### ISSUE TITLE
Numbers starting with decimal point not recognised after /

### ISSUE THREAD

**Issue by ivorget** [tranleduy2000/ncalc#27]
Thanks for the great calculator.

There seems to be a parsing bug in the scientific calculator view - the following doesn't work:
1/.5
It works ok with:
1/0.5
1/(.5)
The other basic operators + - × don't seem have the same problem.

**Comment by axkr** [comment]
Please type `1/0.5` or `1/ .5` (with a space between / and .

The operator `a /. b` is interpreted as `ReplaceAll[a,b]`

Example: in version 3.4.1. in IDE mode type:
```
    f(a)+f(b) /. f(x_)->x^2
    a^2+b^2
```
