### ISSUE TITLE
Unit name & conversion factor

### ISSUE THREAD

**Issue by daniel-edler** [tranleduy2000/ncalc#3]
Two small things:
* The Unit of Energy is called "Joule" and not "Jun". Interestingly you used the internal name energyunitjoules. And I also never saw Jun as some sort of abbreviation for Joule (neither in German nor in English)
* The conversion from Celsius to Kelvin is -273.15 and not -273. Btw. are negative numbers even possible to enter?

P.S. contact me if you want a german localization for your program

**Comment by EinBaum** [comment]
Jun -> Joule has already been fixed.
