### ISSUE TITLE
Feature request: arithmetic and geometric progressions

### ISSUE THREAD

**Issue by ifmihai** [tranleduy2000/ncalc#31]
Do you find this type of calculation useful? 

It would be useful to display, 
Besides the elements in the sequence, 
The partial sums

Like
Start = 0
Step = 1

0 1 2 3 4 5 6 7 
0 1 3 6 10 15 21 28

**Comment by axkr** [comment]
In version 3.4.1 in IDE mode write: 
```
    s=0;Table(s=i+s, {i, 0, 7})

    {0,1,3,6,10,15,21,28}
```
