### ISSUE TITLE
non-lite app uploaded here?

### ISSUE THREAD

**Issue by cheeseman1997** [tranleduy2000/ncalc#36]
Dear @tranleduy2000 ,
It would be great,if you could upload the non-lite app here on github /or at the play store,since it is a great app, yet not everyone can afford a near-nuclear-power-plant pc, which has enough resource to be able to use and make the app out from the files, you have shared with us.
If someone had asked the same, then please ignore it.
Good luck developping such great apps like this!
Yours sincerely,
Cheeseman

**Comment by axkr** [comment]
You can download the APK here:
* https://github.com/tranleduy2000/ncalc/releases
