### ISSUE TITLE
Derivative: Wrong answer

### ISSUE THREAD

**Issue by LenticularAurora** [tranleduy2000/ncalc#42]
When trying to derive the function: (x+2)/(x-3) the answer I get when using this calculator is: (-3+x)^-1 + (x-2)/(3-x)^2 which later results to the following answer: (2x−5)/(3-x)^2 and that is the wrong answer for the first derivative of this function. The correct answer for the first derivative of the this function should be: (5)/(x-3)^2

**Comment by axkr** [comment]
In version 3.4.1 in IDE mode type `D((x+2)/(x-3),x) // simplify`.

**Note** you have to use an upper case `D` for partial derivatives which is different from lower case `d`

**Comment by axkr** [comment]
Fixed with 3.4.3-beta
