### ISSUE TITLE
Feature request: arbitrary bases

### ISSUE THREAD

**Issue by tolziplohu** [tranleduy2000/ncalc#58]
Instead of just decimal, octal, binary, and hexadecimal, it would be nice if you could use any base below 16, say, base 6 or 12.

**Comment by axkr** [comment]
You can use the `^^` operator, which can be used for integer number bases other than 10. Here's an example for a hexadecimal number:

```
>> 16^^abcdefff
2882400255
```

and the `BaseForm` function:
- https://github.com/axkr/symja_android_library/blob/master/symja_android_library/doc/functions/BaseForm.md
