### ISSUE TITLE
Adding calculator to F-Droid

### ISSUE THREAD

**Issue by nicd23** [tranleduy2000/ncalc#6]
It would be amazing to see the calculator on F-Droid.

**Comment by Jorgeelalto** [comment]
Yes, it would be in fact the most powerful of all the calculators there. The thing is, the licensing policy there is pretty restrictive, and if this project uses any libraries that are not open or something...

**Comment by IzzySoft** [comment]
It would help having the `.apk` attached to the `releases/`. It was once in this repo, but now it's gone – so it can no longer be updated [here](https://apt.izzysoft.de/fdroid/index/apk/com.duy.calculator.free) as I don't compile from sources but take the APK offered by the resp. devs directly.

**Comment by axkr** [comment]
Same as  #61
