### ISSUE TITLE
Bug relating to exponential notation

### ISSUE THREAD

**Issue by EternityForest** [tranleduy2000/ncalc#60]
When you type 10^10, press enter, and then divide the result by 10^10, you don't get one, you get another expression in exponential that seems to involve the constant E.

Maybe E notation should be abandoned for x*10^y directly, or e should be used for the constant and E for E notation?

**Comment by axkr** [comment]
Here is an suggestion to mimic the Mathematica output format in a [DoubleToMMAFormat .java](https://gist.github.com/axkr/4e3e895505e75ed32a52128d1862a267)

**Comment by axkr** [comment]
Fixed with 3.4.3-beta

**Comment by axkr** [comment]
PLease reopen if necessary
