### ISSUE TITLE
Create special dialogues 

### ISSUE THREAD

**Issue by axkr** [tranleduy2000/ncalc#67]
Can we have dialogues with sliders which manipulate an output field like in Manipulate:
- https://reference.wolfram.com/language/ref/Manipulate.html

**Comment by tranleduy2000** [comment]
What does it mean?

**Comment by axkr** [comment]
Example for a JavaScript library with this functionality:
* https://github.com/paulmasson/mathcell

**Comment by tranleduy2000** [comment]
In Android, Webview is not fast enough to show too many LaTeX expressions in same time. The latency is about 1 expression / 1 second. I'll replace KaTeX WebView by some native libraries I found on Github for the best performance. 

For plotting, I see some JS libraries can handle this feature.
Ref https://jsxgraph.uni-bayreuth.de/wp/index.html
This library is robust for plotting, the performance in Android webview is not fast as native code, but I think it is acceptable.

**Comment by axkr** [comment]
What's the preferred way to add Android SeekBar's programmatically in IDEActivity result view?
Same question for a "Plot view"?

**Comment by axkr** [comment]
[Manipulate](https://github.com/axkr/symja_android_library/blob/master/symja_android_library/doc/functions/Manipulate.md) is available in latest release through JavaScript libraries. 
For special bugs please open separate issues
