### ISSUE TITLE
Bug in sum

### ISSUE THREAD

**Issue by ValerioVG** [tranleduy2000/ncalc#76]
When performing 9.95 + 2.95, the result has floating point rounding errors: 12.899999999999999

The waiter could not write all the 9s in the card machine, despite his efforts. Please fix.

![Screenshot_20191031-024203](https://user-images.githubusercontent.com/11751054/67914968-90cdab80-fb89-11e9-8849-f86c32301907.png)

**Comment by axkr** [comment]
Which version do you use?

**Comment by ValerioVG** [comment]
The version number is not shown in the About section, but I don't see available updates in Google Play so it should be the latest one.

**Comment by ValerioVG** [comment]
Just tried the apk you linked and the issue disappeared. Thanks

**Comment by tranleduy2000** [comment]
@ValerioVG  You can get the official beta release at https://play.google.com/apps/testing/com.duy.calculator.free
