### ISSUE TITLE
PI calculator might has some problems

### ISSUE THREAD

**Issue by WangberlinT** [tranleduy2000/ncalc#83]
When input is less than 17, the result always 3.14159.
precision: 17, result = 3.1415926535897932, 16 numbers after decimal point.
I'm not sure what is the definition of precision here. 
when input precision is larger or equal than 17, the result always has N-1 numbers after decimal point.
precision: 18, result = 3.14159265358979323, 17 numbers after decimal point.

**Comment by Hello-GS** [comment]
I can fix it.

**Comment by coda953** [comment]
Let him fix the bug @Hello-GS
