### ISSUE TITLE
Incorrect angle value

### ISSUE THREAD

**Issue by RuiqiZheng** [tranleduy2000/ncalc#86]
**Describe the bug**

In the 2D Cartesian Geometry module, after entering the values of two points, the line length, and the angle with Ox axis will be displayed. However, the angle has not been calculated correctly. I gave two examples below.

**Expected behavior**

after entering the values of two points, the line length, and the angle with the Ox axis will be displayed correctly.

**To Reproduce**

1. Open NCalc+ (Which is build from latest source code)
2. Go to 2D Cartesian Geometry module
3. Choose the straight line
4. Enter the value of the start point and the end point
5. Incorrect angle value has been displayed.

**Configuration**

- Android version 9

- device MI 8 Lite

**Screenshots**
![angleProblem1](https://user-images.githubusercontent.com/47793809/83343677-328bc580-a330-11ea-9730-4777d40f4236.jpg)
![angleProblem2](https://user-images.githubusercontent.com/47793809/83343695-6830ae80-a330-11ea-8160-064b041d0fe7.jpg)

**Comment by modashy** [comment]
I have fixed this issue and give a Pull Request.
